# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstWeek' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 4.0.0'
  # Pods for FirstWeek

  target 'FirstWeekTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstWeekUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
